### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard-module#18]
@superdweebie, I've been working on an API module that requires CORS. I know we have `options` method listeners in `shard-module`, but for CORS to work correctly, we need to add headers to each request.

eg. If we want to do

``` curl
GET /rest/users
```

We would need to add the following to each request:

``` php
$result->addHeader(
    GenericHeader::fromString(
        'Access-Control-Allow-Origin: *' //or a specific domain
    )
);
```

For now I've created my own CORS listener: http://goo.gl/0P148A but should we create one for `shard-module` so we can use it like the following:

``` php
'getList' => [
    'zoop.shardmodule.listener.getlist',
    'zoop.shardmodule.listener.cors', //add here
    'zoop.shardmodule.listener.serialize',
    'zoop.shardmodule.listener.prepareviewmodel'
],
```

OR should we instead make a global setting? I know this makes it less flexible, but it also reduces the amount of config needed for each endpoint.

**Comment by superdweebie** [comment]
@crimsonronin sounds like you have a good understanding of the options. I don't know enough about the use case to say which is best. You could also extend the rest controller, which may be a middle way. Or, we could add a feature to shard-module to handle CORS headers. The four options are probably:
- Ignore shard and hook into a zf2 event and set the header every request.
- Extend the shard-module rest controller. To do that, add the following to module config:

```
    'controllers' => [
        'factories' => [
            'shard.rest.MYENDPOINT' => 'MYENDPOINTControllerFactory'
        ],
    ],
```

Then in `MYENDPOINTControllerFactory` return a controller instance that extends `Zoop\ShardModule\Controller\RestfulController` and override the `dispatch` method to insert CORS headers for every request to `MYENDPOINT`. In doing this, you are providing your own custom factory and controller for a specific controller, rather than using the generic `Zoop\ShardModule\Service\RestControllerAbstractFactory`. (this is what `gomi-module` does)
- Change `shard-module` itself, so we can set CORS header options as part of rest endpoint config that then get magically added.
- Write a custom cors listener, as you have suggested, and then add it to endpoint config where it is needed. This option has the finest grain control. ie, it could be added to a `get`, while left disabled on a `put`.

Hope that helps.

**Comment by joshystuart** [comment]
Thanks for your thoughts.

For now I've gone with the custom listener. But I think I might add some additional config in `shard-module` to turn it on "globally", which can then be overridden on each method. I like the controller approach though.

**Comment by joshystuart** [comment]
I'll close this one for now because I have a working solution. I will open a PR when I get a chance with a global CORS setting.
